CREATE TABLE IF NOT EXISTS user (
    user_id VARCHAR(36) PRIMARY KEY,
    uuid VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS match_history (
    id INT PRIMARY KEY AUTO_INCREMENT,
    winner_uuid VARCHAR(255) NOT NULL,
    loser_uuid VARCHAR(255) NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    score INT DEFAULT 0,
    FOREIGN KEY (winner_uuid) REFERENCES user (uuid),
    FOREIGN KEY (loser_uuid) REFERENCES user (uuid)
);